/**
 * Development seed data. These are realistic, plausible activities around the
 * Antwerpen / Kempen region (Mingo's first market) — but they are SAMPLE
 * catalogue entries, NOT a live availability feed. Prices, opening hours and
 * booking links are illustrative. `npm run db:seed:build` turns this into
 * seed/seed.sql.
 */

export interface SeedActivity {
  slug: string;
  title: string;
  description: string;
  category: string;
  location: string;
  lat: number;
  lng: number;
  priceCents: number | null;
  priceBand: "free" | "0_10" | "10_25" | "25_50" | "50_100" | "100_plus";
  durationMin: number | null;
  website?: string;
  booking?: string;
  ticket?: string;
  minAge?: number;
  tags: string[];
}

export const CATEGORIES: { id: string; label: string; icon: string }[] = [
  { id: "sport", label: "Sport", icon: "🏅" },
  { id: "adventure", label: "Adventure", icon: "🧗" },
  { id: "food_drinks", label: "Food & Drinks", icon: "🍽️" },
  { id: "nightlife", label: "Nightlife", icon: "🌃" },
  { id: "creative", label: "Creative", icon: "🎨" },
  { id: "relaxation", label: "Relaxation", icon: "🧖" },
  { id: "culture", label: "Culture", icon: "🏛️" },
  { id: "nature", label: "Nature", icon: "🌲" },
  { id: "gaming", label: "Gaming", icon: "🎮" },
  { id: "entertainment", label: "Entertainment", icon: "🎬" },
  { id: "learning", label: "Learning", icon: "📚" },
  { id: "other", label: "Other", icon: "✨" },
];

export const ACTIVITIES: SeedActivity[] = [
  {
    slug: "padel-hoogstraten",
    title: "Padel doubles",
    description:
      "Book a court for four and settle who actually has a backhand. Rackets and balls available on site; indoor courts so rain is not an excuse.",
    category: "sport",
    location: "Padel Hoogstraten, Hoogstraten",
    lat: 51.4009,
    lng: 4.7591,
    priceCents: 1500,
    priceBand: "10_25",
    durationMin: 90,
    website: "https://www.example-padel-hoogstraten.be",
    booking: "https://www.example-padel-hoogstraten.be/reserveren",
    tags: ["indoor", "team", "beginner-friendly"],
  },
  {
    slug: "bowling-turnhout",
    title: "Bowling night",
    description:
      "Two lanes, bumper wars optional, nachos non-negotiable. Shoe rental included in the lane price.",
    category: "entertainment",
    location: "Stadionlaan Bowling, Turnhout",
    lat: 51.3226,
    lng: 4.9441,
    priceCents: 1200,
    priceBand: "10_25",
    durationMin: 120,
    booking: "https://www.example-bowling-turnhout.be/book",
    tags: ["indoor", "classic", "any-weather"],
  },
  {
    slug: "escape-room-antwerp",
    title: "Escape room: The Vault",
    description:
      "60 minutes to crack a 1920s bank vault before the alarm. Best with 3–5 people who can stay calm while someone yells about a keypad.",
    category: "gaming",
    location: "Sleutelgat Escape, Antwerpen",
    lat: 51.2194,
    lng: 4.4025,
    priceCents: 2400,
    priceBand: "10_25",
    durationMin: 75,
    booking: "https://www.example-escape-antwerp.be/the-vault",
    minAge: 12,
    tags: ["puzzles", "teamwork", "indoor"],
  },
  {
    slug: "kayak-kleine-nete",
    title: "Kayak the Kleine Nete",
    description:
      "A calm 8 km paddle through the Kempen countryside. No experience needed; you will still get splashed.",
    category: "adventure",
    location: "Kayak Kempen, Kasterlee",
    lat: 51.2426,
    lng: 4.9698,
    priceCents: 2200,
    priceBand: "10_25",
    durationMin: 150,
    booking: "https://www.example-kayak-kempen.be",
    minAge: 10,
    tags: ["outdoor", "water", "summer"],
  },
  {
    slug: "brunch-antwerp-zuid",
    title: "Long brunch at Het Zuid",
    description:
      "Bottomless coffee, eggs done properly, and a table you can keep for two hours. Reserve for groups of 4+.",
    category: "food_drinks",
    location: "Café Zuiderterras area, Antwerpen Zuid",
    lat: 51.2093,
    lng: 4.3901,
    priceCents: 2500,
    priceBand: "25_50",
    durationMin: 120,
    booking: "https://www.example-brunch-zuid.be",
    tags: ["daytime", "cosy", "vegetarian-options"],
  },
  {
    slug: "cocktail-class-antwerp",
    title: "Cocktail-making class",
    description:
      "A bartender teaches you three classics, you make (and drink) all three. Includes snacks. 21+ for the tasting.",
    category: "nightlife",
    location: "Shaker Studio, Antwerpen",
    lat: 51.2177,
    lng: 4.4123,
    priceCents: 4500,
    priceBand: "25_50",
    durationMin: 120,
    booking: "https://www.example-shaker-antwerp.be/classes",
    minAge: 18,
    tags: ["hands-on", "evening", "drinks"],
  },
  {
    slug: "pottery-workshop-mechelen",
    title: "Wheel-throwing pottery workshop",
    description:
      "Two hours at the wheel making a wonky bowl you will absolutely keep forever. Clay, tools and firing included; pieces shipped after two weeks.",
    category: "creative",
    location: "Klei Atelier, Mechelen",
    lat: 51.0281,
    lng: 4.4801,
    priceCents: 5500,
    priceBand: "50_100",
    durationMin: 120,
    booking: "https://www.example-klei-mechelen.be",
    tags: ["hands-on", "indoor", "calm"],
  },
  {
    slug: "spa-day-kalmthout",
    title: "Half-day spa & sauna",
    description:
      "Finnish sauna, steam room, plunge pool and a lot of lying around. Bring flip-flops. Towels rentable on site.",
    category: "relaxation",
    location: "Thermen Heide, Kalmthout",
    lat: 51.3894,
    lng: 4.4304,
    priceCents: 3900,
    priceBand: "25_50",
    durationMin: 240,
    booking: "https://www.example-thermen-heide.be",
    minAge: 16,
    tags: ["quiet", "indoor", "wellness"],
  },
  {
    slug: "mas-museum-antwerp",
    title: "MAS museum + rooftop",
    description:
      "Ten floors of Antwerp's history and a free rooftop with the best skyline view in the city. Go late afternoon for the light.",
    category: "culture",
    location: "MAS | Museum aan de Stroom, Antwerpen",
    lat: 51.2288,
    lng: 4.4051,
    priceCents: 1200,
    priceBand: "10_25",
    durationMin: 120,
    website: "https://www.example-mas.be",
    ticket: "https://www.example-mas.be/tickets",
    tags: ["indoor", "view", "rainy-day"],
  },
  {
    slug: "hike-kalmthoutse-heide",
    title: "Kalmthoutse Heide walk",
    description:
      "A 10 km loop through heath, drifting sand and pine. Flat, well-marked, and there is a pancake house at the end.",
    category: "nature",
    location: "Kalmthoutse Heide, Kalmthout",
    lat: 51.3985,
    lng: 4.4045,
    priceCents: 0,
    priceBand: "free",
    durationMin: 180,
    website: "https://www.example-grensparkzk.be",
    tags: ["outdoor", "free", "dog-friendly"],
  },
  {
    slug: "boardgame-cafe-antwerp",
    title: "Board-game café afternoon",
    description:
      "300+ games on the shelf, a host who explains the rules, and drinks table service. Pay per person for the whole session.",
    category: "gaming",
    location: "De Meeple, Antwerpen",
    lat: 51.2141,
    lng: 4.4189,
    priceCents: 700,
    priceBand: "0_10",
    durationMin: 180,
    website: "https://www.example-demeeple.be",
    tags: ["indoor", "cosy", "any-weather"],
  },
  {
    slug: "comedy-night-antwerp",
    title: "Stand-up comedy night",
    description:
      "A rotating line-up of Dutch and English sets in a small room where the front row is a risk. Doors 19:30, show 20:00.",
    category: "entertainment",
    location: "Kap Comedy Club, Antwerpen",
    lat: 51.2166,
    lng: 4.4106,
    priceCents: 1800,
    priceBand: "10_25",
    durationMin: 120,
    ticket: "https://www.example-kapcomedy.be/tickets",
    minAge: 16,
    tags: ["evening", "indoor", "drinks"],
  },
  {
    slug: "climbing-gym-antwerp",
    title: "Indoor climbing session",
    description:
      "Bouldering and rope walls for all levels. First-timers get a 20-minute safety intro. Shoe rental available.",
    category: "sport",
    location: "Klimzaal Aapies, Antwerpen",
    lat: 51.2308,
    lng: 4.3881,
    priceCents: 1600,
    priceBand: "10_25",
    durationMin: 120,
    booking: "https://www.example-aapies.be",
    minAge: 8,
    tags: ["indoor", "active", "any-weather"],
  },
  {
    slug: "wine-tasting-antwerp",
    title: "Natural wine tasting",
    description:
      "Six low-intervention wines with a sommelier who is genuinely funny about it. Cheese and bread included.",
    category: "food_drinks",
    location: "Glou Glou, Antwerpen",
    lat: 51.2189,
    lng: 4.4267,
    priceCents: 3500,
    priceBand: "25_50",
    durationMin: 120,
    booking: "https://www.example-glouglou.be",
    minAge: 18,
    tags: ["evening", "drinks", "seated"],
  },
  {
    slug: "karting-mechelen",
    title: "Indoor karting Grand Prix",
    description:
      "Electric karts, timed heats and a podium ceremony that people take far too seriously. Race suits provided.",
    category: "adventure",
    location: "Circuit Mechelen-Zuid, Mechelen",
    lat: 51.0163,
    lng: 4.4776,
    priceCents: 3200,
    priceBand: "25_50",
    durationMin: 90,
    booking: "https://www.example-karting-mechelen.be",
    minAge: 14,
    tags: ["indoor", "adrenaline", "competitive"],
  },
  {
    slug: "life-drawing-antwerp",
    title: "Life-drawing session",
    description:
      "Two hours, one model, timed poses from 1 to 20 minutes. Materials provided, all skill levels, no critique.",
    category: "creative",
    location: "Academie Studio, Antwerpen",
    lat: 51.2201,
    lng: 4.4008,
    priceCents: 1400,
    priceBand: "10_25",
    durationMin: 120,
    booking: "https://www.example-lifedrawing-antwerp.be",
    minAge: 18,
    tags: ["indoor", "calm", "hands-on"],
  },
  {
    slug: "cinema-antwerp",
    title: "Arthouse cinema double bill",
    description:
      "Two curated films with a break for a drink between. Bar open before and after.",
    category: "entertainment",
    location: "Cinema Cartoon's, Antwerpen",
    lat: 51.2233,
    lng: 4.4009,
    priceCents: 2000,
    priceBand: "10_25",
    durationMin: 240,
    ticket: "https://www.example-cartoons-cinema.be",
    tags: ["indoor", "evening", "rainy-day"],
  },
  {
    slug: "farm-dinner-hoogstraten",
    title: "Farm-to-table group dinner",
    description:
      "A four-course set menu on a working farm outside Hoogstraten. One long table, everyone eats the same thing, it is excellent.",
    category: "food_drinks",
    location: "Hoeve De Strik, Hoogstraten",
    lat: 51.3987,
    lng: 4.7369,
    priceCents: 6500,
    priceBand: "50_100",
    durationMin: 180,
    booking: "https://www.example-hoevedestrik.be",
    tags: ["evening", "seated", "special-occasion"],
  },
  {
    slug: "yoga-park-antwerp",
    title: "Outdoor vinyasa yoga",
    description:
      "A 75-minute flow in Park Spoor Noord, all levels. Bring your own mat. Cancelled if it rains — you get a rain-check.",
    category: "relaxation",
    location: "Park Spoor Noord, Antwerpen",
    lat: 51.2273,
    lng: 4.4184,
    priceCents: 1000,
    priceBand: "0_10",
    durationMin: 75,
    booking: "https://www.example-yoga-antwerp.be",
    tags: ["outdoor", "morning", "summer"],
  },
  {
    slug: "brewery-tour-antwerp",
    title: "Brewery tour & tasting",
    description:
      "Behind the scenes at a city brewery, ending with four beers and a pretzel. 90 minutes, lots of stairs.",
    category: "food_drinks",
    location: "De Koninck / city brewery, Antwerpen",
    lat: 51.1996,
    lng: 4.4142,
    priceCents: 1900,
    priceBand: "10_25",
    durationMin: 90,
    ticket: "https://www.example-brewery-antwerp.be/tour",
    minAge: 18,
    tags: ["indoor", "drinks", "guided"],
  },
  {
    slug: "laser-tag-turnhout",
    title: "Laser tag arena",
    description:
      "Three rounds in a two-level blacklight arena. Teams of up to 8. Wear dark clothes for the full effect.",
    category: "gaming",
    location: "Blackout Arena, Turnhout",
    lat: 51.3183,
    lng: 4.9556,
    priceCents: 1400,
    priceBand: "10_25",
    durationMin: 75,
    booking: "https://www.example-blackout-turnhout.be",
    minAge: 8,
    tags: ["indoor", "active", "teams"],
  },
  {
    slug: "street-art-tour-antwerp",
    title: "Street-art walking tour",
    description:
      "A local guide walks you through the murals and paste-ups of Antwerpen-Noord and the stories behind them. 2 hours, flat route.",
    category: "culture",
    location: "Antwerpen-Noord (meet at Stuivenberg)",
    lat: 51.2261,
    lng: 4.4315,
    priceCents: 1500,
    priceBand: "10_25",
    durationMin: 120,
    booking: "https://www.example-streetart-antwerp.be",
    tags: ["outdoor", "walking", "guided"],
  },
  {
    slug: "minigolf-antwerp",
    title: "Glow-in-the-dark minigolf",
    description:
      "18 blacklit holes indoors, plus a bar. Genuinely good fun even if you claim to be too old for it.",
    category: "entertainment",
    location: "Blacklight Golf, Antwerpen",
    lat: 51.2119,
    lng: 4.4213,
    priceCents: 1100,
    priceBand: "10_25",
    durationMin: 75,
    booking: "https://www.example-blacklightgolf.be",
    tags: ["indoor", "any-weather", "casual"],
  },
  {
    slug: "cook-along-mechelen",
    title: "Thai cook-along dinner",
    description:
      "Cook a three-dish Thai menu together with a chef, then sit down and eat it as a group. Aprons and recipes to take home.",
    category: "learning",
    location: "Kookstudio Dijle, Mechelen",
    lat: 51.0259,
    lng: 4.4778,
    priceCents: 5900,
    priceBand: "50_100",
    durationMin: 180,
    booking: "https://www.example-kookstudio-dijle.be",
    tags: ["hands-on", "evening", "food"],
  },
  {
    slug: "bike-tour-scheldt",
    title: "Sunset bike ride along the Scheldt",
    description:
      "A relaxed 20 km ride to the polders south of the city and back, timed to end at golden hour. Bring or rent a bike.",
    category: "nature",
    location: "Sint-Annastrand, Antwerpen (Linkeroever)",
    lat: 51.2151,
    lng: 4.3823,
    priceCents: 0,
    priceBand: "free",
    durationMin: 150,
    tags: ["outdoor", "free", "evening"],
  },
  {
    slug: "vr-arcade-antwerp",
    title: "VR arcade hour",
    description:
      "Free-roam VR: co-op shooters, puzzle rooms and one very unsettling plank experience. Booths for up to 4.",
    category: "gaming",
    location: "Portal VR, Antwerpen",
    lat: 51.2098,
    lng: 4.4162,
    priceCents: 2800,
    priceBand: "25_50",
    durationMin: 60,
    booking: "https://www.example-portalvr.be",
    minAge: 12,
    tags: ["indoor", "tech", "any-weather"],
  },
  {
    slug: "darts-social-antwerp",
    title: "Social darts night",
    description:
      "Automated boards that keep score for you, booth hire by the hour, kitchen until late. Up to 6 per oche.",
    category: "nightlife",
    location: "Bull's Antwerpen",
    lat: 51.2172,
    lng: 4.4205,
    priceCents: 1300,
    priceBand: "10_25",
    durationMin: 120,
    booking: "https://www.example-bulls-antwerp.be",
    minAge: 18,
    tags: ["evening", "indoor", "drinks"],
  },
  {
    slug: "improv-workshop-antwerp",
    title: "Intro to improv workshop",
    description:
      "A low-pressure two-hour taster: games, scenes and a lot of laughing at yourselves. No experience, no audience.",
    category: "learning",
    location: "Improv Lab, Antwerpen",
    lat: 51.2205,
    lng: 4.4155,
    priceCents: 2000,
    priceBand: "10_25",
    durationMin: 120,
    booking: "https://www.example-improvlab-antwerp.be",
    minAge: 16,
    tags: ["indoor", "social", "hands-on"],
  },
  {
    slug: "picnic-middelheim",
    title: "Sculpture-park picnic",
    description:
      "Bring food, blankets and a frisbee to the open-air Middelheim museum. Free entry, 40+ hectares, Rodin included.",
    category: "nature",
    location: "Middelheimmuseum, Antwerpen",
    lat: 51.1852,
    lng: 4.4147,
    priceCents: 0,
    priceBand: "free",
    durationMin: 180,
    website: "https://www.example-middelheim.be",
    tags: ["outdoor", "free", "daytime"],
  },
  {
    slug: "axe-throwing-antwerp",
    title: "Axe throwing",
    description:
      "Coached lanes, hatchets, and a surprising amount of technique. Closed-toe shoes required. Teams of 2–6.",
    category: "adventure",
    location: "Timber Antwerpen",
    lat: 51.2246,
    lng: 4.4291,
    priceCents: 2500,
    priceBand: "25_50",
    durationMin: 90,
    booking: "https://www.example-timber-antwerp.be",
    minAge: 16,
    tags: ["indoor", "adrenaline", "coached"],
  },
];
