/**
 * Generates seed/seed.sql from:
 *   - the hand-curated catalogue  (seed/activities.ts)
 *   - the OpenStreetMap import    (seed/osm/osm-activities.json, optional)
 *
 *   npm run db:seed:build          (regenerate the SQL)
 *   npm run db:seed:local|:remote  (regenerate + apply)
 *
 * The SQL is idempotent — INSERT OR REPLACE keyed on deterministic ids — so it
 * is safe to re-run after adding, editing or re-importing an activity.
 *
 * Everything ships status = 'needs_review'. A human flips rows to 'verified' in
 * the Command Center after re-checking. Nothing here is invented: OSM rows carry
 * real names / coordinates / websites; prices are indicative BANDS only.
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  ACTIVITIES,
  CATEGORIES,
  SEED_VERIFIED_ON,
  activityImageUrl,
  type SeedActivity,
} from "./activities";
import { resolvePlace } from "../src/worker/lib/be-places";

const here = dirname(fileURLToPath(import.meta.url));
const q = (s: string | null | undefined) =>
  s == null ? "NULL" : `'${s.replace(/'/g, "''")}'`;
const n = (v: number | null | undefined) => (v == null ? "NULL" : String(v));

const now = Math.floor(Date.now() / 1000);
const verifiedAt = Math.floor(new Date(`${SEED_VERIFIED_ON}T12:00:00Z`).getTime() / 1000);
const PROV_WEB = "prov_web";
const PROV_OSM = "prov_osm";

/* ------------------------------ OSM import ------------------------------ */
interface OsmActivity extends SeedActivity {
  source: "osm";
  imageUrl: string | null;
  imageAttribution: string | null;
  osmId: string;
}

const osmPath = join(here, "osm", "osm-activities.json");
const OSM: OsmActivity[] = existsSync(osmPath)
  ? (JSON.parse(readFileSync(osmPath, "utf8")) as OsmActivity[])
  : [];

/** normalised token set for a fuzzy name compare */
const tokens = (s: string) =>
  new Set(
    s
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, " ")
      .split(" ")
      .filter((w) => w.length > 2),
  );
const overlap = (a: Set<string>, b: Set<string>) => {
  if (!a.size || !b.size) return 0;
  let hit = 0;
  for (const w of a) if (b.has(w)) hit++;
  return hit / Math.min(a.size, b.size);
};
const km = (aLat: number, aLng: number, bLat: number, bLng: number) => {
  const R = 6371;
  const dLat = ((bLat - aLat) * Math.PI) / 180;
  const dLng = ((bLng - aLng) * Math.PI) / 180;
  const x =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((aLat * Math.PI) / 180) *
      Math.cos((bLat * Math.PI) / 180) *
      Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(x));
};

// drop OSM rows that are really the same place as a curated one (curated wins —
// it has a written description + a hand-picked photo)
const curatedGeo = ACTIVITIES.filter((a) => a.lat != null && a.lng != null).map((a) => ({
  t: tokens(a.title),
  lat: a.lat!,
  lng: a.lng!,
}));
const dedupedOsm = OSM.filter((o) => {
  if (o.lat == null || o.lng == null) return false;
  const ot = tokens(o.title);
  return !curatedGeo.some(
    (c) => km(c.lat, c.lng, o.lat!, o.lng!) < 0.2 && overlap(ot, c.t) >= 0.55,
  );
});

/* ------------------------------ SQL header ----------------------------- */
const lines: string[] = [
  "-- Generated by seed/build-seed.ts — do not edit by hand.",
  `-- Curated set verified ${SEED_VERIFIED_ON}. OSM rows © OpenStreetMap contributors (ODbL).`,
  "-- Everything ships status='needs_review'.",
  "PRAGMA foreign_keys=OFF;",
  "",
  `INSERT OR REPLACE INTO providers (id, name, kind, enabled, config, created_at)`,
  `VALUES (${q(PROV_WEB)}, 'VIBIN curated (web sources)', 'dataset', 1, '{}', ${now});`,
  `INSERT OR REPLACE INTO providers (id, name, kind, enabled, config, created_at)`,
  `VALUES (${q(PROV_OSM)}, 'OpenStreetMap contributors (ODbL)', 'dataset', 1, '{}', ${now});`,
  "",
];

// Upsert (not INSERT OR REPLACE): keeps label/icon/sort in sync with the code
// constant on every reseed, but never touches `active` — an admin's
// activate/deactivate choice in the Command Center must survive a reseed.
CATEGORIES.forEach((c, i) => {
  lines.push(
    `INSERT INTO activity_categories (id, label, icon, sort) VALUES (${q(
      c.id,
    )}, ${q(c.label)}, ${q(c.icon)}, ${i}) ` +
      `ON CONFLICT(id) DO UPDATE SET label=excluded.label, icon=excluded.icon, sort=excluded.sort;`,
  );
});
lines.push("");

const COLS = [
  "id", "provider_id", "external_id", "title", "description", "category_id",
  "subcategory", "provider", "provider_website", "location_label", "address",
  "city", "country", "lat", "lng", "price_cents", "price_type", "price_band",
  "currency", "duration_min", "min_participants", "max_participants", "min_age",
  "indoor_outdoor", "accessibility", "opening_hours", "website_url",
  "booking_url", "ticket_url", "image_url", "image_source", "image_attribution",
  "tags", "source", "source_url", "last_verified_at", "status", "active",
  "image_is_generic",
  // monetization (§4/§46) — computed the same as `status` above: a plain,
  // honest fact from the data itself ("outbound_tracking" when there's a
  // real link to measure, "none" otherwise), never a guessed deal. Affiliate
  // URL / network / commission columns are deliberately NOT emitted here —
  // like `status`, they reset to their safe default ("no deal") on every
  // reseed, same as an admin's "verified" mark does today; an admin sets a
  // real deal by hand in the Command Center after the catalogue is seeded,
  // and re-running the seed (e.g. to add more OSM data) will wipe it, exactly
  // as it already wipes a hand-verified status. Documented, not new.
  "monetization_type",
  "created_at", "updated_at",
];

let missingCoords = 0;

function emit(
  a: SeedActivity,
  opts: {
    providerId: string;
    source: string;
    imageUrl?: string | null;
    imageAttribution?: string | null;
  },
) {
  const id = `act_${a.slug}`;
  const locationLabel = `${a.provider}, ${a.city}`;
  const cc = a.lat == null || a.lng == null ? resolvePlace(a.city) : null;
  const lat = a.lat ?? cc?.lat ?? null;
  const lng = a.lng ?? cc?.lng ?? null;
  if (lat == null || lng == null) {
    missingCoords++;
    return;
  }

  // image: a real venue photo from the source wins; else the shared resolver
  // (venue slug → hand Unsplash → subcategory → category). `imageIsGeneric`
  // tracks whether the final photo is specific to this venue/activity (a
  // per-node OSM photo, a curated venue shot, or a hand-picked activity
  // photo) or a shared category/subcategory stock fallback used across many
  // unrelated activities — the honest signal the image-quality audit (§28)
  // surfaces instead of silently letting reuse look like a bug.
  let imgUrl = opts.imageUrl ?? null;
  let imgSource = opts.imageUrl ? "Wikimedia Commons" : null;
  let imgAttr = opts.imageAttribution ?? null;
  let imgIsGeneric = false;
  if (!imgUrl) {
    const r = activityImageUrl(a.slug, a.category, a.subcategory);
    if (r) {
      imgUrl = r.url;
      imgSource = r.source;
      imgAttr = r.attribution;
      imgIsGeneric = r.generic;
    }
  }

  const vals = [
    q(id),
    q(opts.providerId),
    q(a.slug),
    q(a.title),
    q(a.description),
    q(a.category),
    q(a.subcategory ?? null),
    q(a.provider),
    q(a.providerWebsite),
    q(locationLabel),
    q(a.address ?? null),
    q(a.city),
    q("BE"),
    n(Math.round(lat * 1e6)),
    n(Math.round(lng * 1e6)),
    n(a.priceCents),
    q(a.priceType),
    q(a.priceBand),
    q("EUR"),
    n(a.durationMin),
    n(a.minParticipants),
    n(a.maxParticipants),
    n(a.minAge),
    q(a.indoorOutdoor ?? null),
    q(a.accessibility ?? null),
    q("{}"),
    q(a.providerWebsite),
    q(a.bookingUrl ?? null),
    q(a.ticketUrl ?? null),
    q(imgUrl),
    q(imgSource),
    q(imgAttr),
    q(JSON.stringify(a.tags)),
    q(opts.source),
    q(a.sourceUrl),
    n(verifiedAt),
    q("needs_review"),
    "1",
    imgIsGeneric ? "1" : "0",
    q(a.providerWebsite || a.bookingUrl || a.ticketUrl ? "outbound_tracking" : "none"),
    n(now),
    n(now),
  ];
  lines.push(
    `INSERT OR REPLACE INTO activities (${COLS.join(", ")}) VALUES (${vals.join(", ")});`,
  );
}

for (const a of ACTIVITIES) emit(a, { providerId: PROV_WEB, source: "web" });
for (const o of dedupedOsm) {
  emit(o, {
    providerId: PROV_OSM,
    source: "osm",
    imageUrl: o.imageUrl,
    imageAttribution: o.imageAttribution,
  });
}

lines.push("", "PRAGMA foreign_keys=ON;", "");

writeFileSync(join(here, "seed.sql"), lines.join("\n"));
const total = ACTIVITIES.length + dedupedOsm.length - missingCoords;
console.log(
  `Wrote seed.sql — ${CATEGORIES.length} categories, ${total} activities ` +
    `(${ACTIVITIES.length} curated + ${dedupedOsm.length} OSM, ${OSM.length - dedupedOsm.length} OSM deduped, ${missingCoords} dropped for no coords).`,
);
