/**
 * Generates seed/seed.sql from the typed catalogue in seed/activities.ts.
 *   npm run db:seed:build          (regenerate the SQL)
 *   npm run db:seed:local|:remote  (regenerate + apply)
 *
 * The SQL is idempotent — INSERT OR REPLACE keyed on deterministic ids — so it
 * is safe to re-run after adding or editing an activity.
 *
 * All seeded activities are inserted with status = 'needs_review' and
 * last_verified_at = the SEED_VERIFIED_ON date. Nothing is marked 'verified'
 * automatically — a human does that in the admin after re-checking.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  ACTIVITIES,
  ACTIVITY_IMAGE_ATTRIBUTION,
  ACTIVITY_IMAGE_SOURCE,
  CATEGORIES,
  CITY_COORDS,
  SEED_VERIFIED_ON,
  activityImageUrl,
} from "./activities";

const here = dirname(fileURLToPath(import.meta.url));
const q = (s: string | null | undefined) =>
  s == null ? "NULL" : `'${s.replace(/'/g, "''")}'`;
const n = (v: number | null | undefined) => (v == null ? "NULL" : String(v));

const now = Math.floor(Date.now() / 1000);
const verifiedAt = Math.floor(new Date(`${SEED_VERIFIED_ON}T12:00:00Z`).getTime() / 1000);
const PROVIDER_ID = "prov_web";

const lines: string[] = [
  "-- Generated by seed/build-seed.ts — do not edit by hand.",
  `-- Catalogue verified on ${SEED_VERIFIED_ON}. Every activity ships as status='needs_review'.`,
  "PRAGMA foreign_keys=OFF;",
  "",
  `INSERT OR REPLACE INTO providers (id, name, kind, enabled, config, created_at)`,
  `VALUES (${q(PROVIDER_ID)}, 'VIBIN curated (web sources)', 'dataset', 1, '{}', ${now});`,
  "",
];

CATEGORIES.forEach((c, i) => {
  lines.push(
    `INSERT OR REPLACE INTO activity_categories (id, label, icon, sort) VALUES (${q(
      c.id,
    )}, ${q(c.label)}, ${q(c.icon)}, ${i});`,
  );
});
lines.push("");

const COLS = [
  "id", "provider_id", "external_id", "title", "description", "category_id",
  "subcategory", "provider", "provider_website", "location_label", "address",
  "city", "country", "lat", "lng", "price_cents", "price_type", "price_band",
  "currency", "duration_min", "min_participants", "max_participants", "min_age",
  "indoor_outdoor", "accessibility", "opening_hours", "website_url",
  "booking_url", "ticket_url", "image_url", "image_source", "image_attribution",
  "tags", "source", "source_url", "last_verified_at", "status", "active",
  "created_at", "updated_at",
];

for (const a of ACTIVITIES) {
  const id = `act_${a.slug}`;
  const locationLabel = `${a.provider}, ${a.city}`;
  const imageUrl = activityImageUrl(a.slug, a.category);
  // Precise venue coordinates win; otherwise fall back to the city centroid so
  // the group radius filter still has a signal. null only if the city is unknown.
  const cc = CITY_COORDS[a.city];
  const lat = a.lat ?? cc?.lat ?? null;
  const lng = a.lng ?? cc?.lng ?? null;
  const vals = [
    q(id),
    q(PROVIDER_ID),
    q(a.slug),
    q(a.title),
    q(a.description),
    q(a.category),
    q(a.subcategory ?? null),
    q(a.provider),
    q(a.providerWebsite),
    q(locationLabel),
    q(a.address ?? null),
    q(a.city),
    q("BE"),
    n(lat != null ? Math.round(lat * 1e6) : null),
    n(lng != null ? Math.round(lng * 1e6) : null),
    n(a.priceCents),
    q(a.priceType),
    q(a.priceBand),
    q("EUR"),
    n(a.durationMin),
    n(a.minParticipants),
    n(a.maxParticipants),
    n(a.minAge),
    q(a.indoorOutdoor ?? null),
    q(a.accessibility ?? null),
    q("{}"),
    q(a.providerWebsite),
    q(a.bookingUrl ?? null),
    q(a.ticketUrl ?? null),
    q(imageUrl), // image_url — hand-matched free-licence photo per activity
    q(imageUrl ? ACTIVITY_IMAGE_SOURCE : null),
    q(imageUrl ? ACTIVITY_IMAGE_ATTRIBUTION : null),
    q(JSON.stringify(a.tags)),
    q("web"),
    q(a.sourceUrl),
    n(verifiedAt),
    q("needs_review"),
    "1",
    n(now),
    n(now),
  ];
  lines.push(
    `INSERT OR REPLACE INTO activities (${COLS.join(", ")}) VALUES (${vals.join(", ")});`,
  );
}

lines.push("", "PRAGMA foreign_keys=ON;", "");

const out = join(here, "seed.sql");
writeFileSync(out, lines.join("\n"));
console.log(
  `Wrote ${out} — ${CATEGORIES.length} categories, ${ACTIVITIES.length} activities (status=needs_review, verified ${SEED_VERIFIED_ON}).`,
);
