/**
 * Generates seed/seed.sql from the typed data in seed/activities.ts.
 * Run with:  npm run db:seed:build
 * Then apply: npm run db:seed:local   (or :remote)
 *
 * The SQL is idempotent — INSERT OR REPLACE keyed on deterministic ids — so it
 * is safe to re-run after adding new activities.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { ACTIVITIES, CATEGORIES } from "./activities";

const here = dirname(fileURLToPath(import.meta.url));
const q = (s: string | null) =>
  s == null ? "NULL" : `'${s.replace(/'/g, "''")}'`;
const now = Math.floor(Date.now() / 1000);
const PROVIDER_ID = "prov_seed";

const lines: string[] = [
  "-- Generated by seed/build-seed.ts — do not edit by hand.",
  "PRAGMA foreign_keys=OFF;",
  "",
  `INSERT OR REPLACE INTO providers (id, name, kind, enabled, config, created_at)`,
  `VALUES (${q(PROVIDER_ID)}, 'Mingo Seed Catalogue', 'seed', 1, '{}', ${now});`,
  "",
];

for (const c of CATEGORIES) {
  lines.push(
    `INSERT OR REPLACE INTO activity_categories (id, label, icon, sort) VALUES (${q(
      c.id,
    )}, ${q(c.label)}, ${q(c.icon)}, ${CATEGORIES.indexOf(c)});`,
  );
}
lines.push("");

for (const a of ACTIVITIES) {
  const id = `act_${a.slug}`;
  const image = `https://picsum.photos/seed/mingo-${a.slug}/1200/900`;
  lines.push(
    `INSERT OR REPLACE INTO activities (id, provider_id, external_id, title, description, category_id, location_label, lat, lng, price_cents, price_band, currency, duration_min, opening_hours, website_url, booking_url, ticket_url, min_age, image_url, tags, source, active, created_at, updated_at) VALUES (` +
      [
        q(id),
        q(PROVIDER_ID),
        q(a.slug),
        q(a.title),
        q(a.description),
        q(a.category),
        q(a.location),
        Math.round(a.lat * 1e6),
        Math.round(a.lng * 1e6),
        a.priceCents == null ? "NULL" : a.priceCents,
        q(a.priceBand),
        q("EUR"),
        a.durationMin == null ? "NULL" : a.durationMin,
        q("{}"),
        q(a.website ?? null),
        q(a.booking ?? null),
        q(a.ticket ?? null),
        a.minAge == null ? "NULL" : a.minAge,
        q(image),
        q(JSON.stringify(a.tags)),
        q("seed"),
        1,
        now,
        now,
      ].join(", ") +
      `);`,
  );
}

lines.push("", "PRAGMA foreign_keys=ON;", "");

const out = join(here, "seed.sql");
writeFileSync(out, lines.join("\n"));
console.log(
  `Wrote ${out} — ${CATEGORIES.length} categories, ${ACTIVITIES.length} activities.`,
);
